package net.ludovicoflaviano.bettersfp.gui;
import net.ludovicoflaviano.bettersfp.data.*;import net.ludovicoflaviano.bettersfp.economy.EconomyHook;import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public final class SpawnerGui {private final JavaPlugin plugin;private final SpawnerStore store;private final EconomyHook economy;private final String title="§8BetterSpawners §7• §fSpawner";private final String storageTitle="§8BetterSpawners §7• §fStorage";public SpawnerGui(JavaPlugin p,SpawnerStore s,EconomyHook e){plugin=p;store=s;economy=e;}
 public void open(Player p,SpawnerData d){Inventory i=Bukkit.createInventory(null,54,title);for(int n=0;n<54;n++)item(i,n,Material.GRAY_STAINED_GLASS_PANE," ");item(i,4,Material.SPAWNER,"§b"+d.entity,"§7Stack: §f"+d.stack,"§7Stored XP: §f"+d.storedXp);item(i,20,Material.CLOCK,"§aSpeed Upgrade §7Lv."+d.speedLevel,"§7Improve production speed","§eClick to buy");item(i,22,Material.GOLD_INGOT,"§6Yield Upgrade §7Lv."+d.yieldLevel,"§7Increase virtual drops","§eClick to buy");item(i,24,Material.CHEST,"§bStorage Upgrade §7Lv."+d.storageLevel,"§7Increase storage capacity","§eClick to buy");item(i,31,Material.CHEST_MINECART,"§fOpen Storage","§7Collect items and XP");item(i,49,Material.BARRIER,"§cClose");p.openInventory(i);}
 public void click(InventoryClickEvent e,SpawnerData d){e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p))return;switch(e.getRawSlot()){case 20->upgrade(p,d,"speed");case 22->upgrade(p,d,"yield");case 24->upgrade(p,d,"storage");case 31->storage(p,d);case 49->p.closeInventory();}}
 private void upgrade(Player p,SpawnerData d,String branch){int max=plugin.getConfig().getInt("settings.max-upgrade-level",10);int level=branch.equals("speed")?d.speedLevel:branch.equals("yield")?d.yieldLevel:d.storageLevel;if(level>=max){p.sendMessage("§cMax level reached.");return;}double cost=plugin.getConfig().getDouble("settings.upgrade-base-cost",50000)*Math.pow(plugin.getConfig().getDouble("settings.upgrade-cost-multiplier",3),level);if(!economy.take(p,cost)){p.sendMessage("§cUpgrade cost: §e"+economy.format(cost));return;}if(branch.equals("speed"))d.speedLevel++;else if(branch.equals("yield"))d.yieldLevel++;else d.storageLevel++;p.sendMessage("§aUpgrade purchased for §e"+economy.format(cost));store.save();open(p,d);}
 private void storage(Player p,SpawnerData d){Inventory i=Bukkit.createInventory(null,54,storageTitle);int n=0;for(var e:d.items.entrySet()){if(n>=45)break;ItemStack it=new ItemStack(e.getKey(),Math.min(64,e.getValue()));ItemMeta m=it.getItemMeta();m.setLore(List.of("§7Stored: §f"+e.getValue(),"§eClick to collect"));it.setItemMeta(m);i.setItem(n++,it);}item(i,49,Material.EXPERIENCE_BOTTLE,"§aStored XP §f"+d.storedXp,"§eClick to collect all");p.openInventory(i);}
 public void storageClick(InventoryClickEvent e,SpawnerData d){e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p))return;if(e.getRawSlot()==49){p.giveExp((int)Math.min(Integer.MAX_VALUE,d.storedXp));d.storedXp=0;storage(p,d);store.save();return;}ItemStack it=e.getCurrentItem();if(it==null||it.getType().isAir())return;Material m=it.getType();int a=Math.min(64,d.items.getOrDefault(m,0));if(a>0){p.getInventory().addItem(new ItemStack(m,a));int left=d.items.get(m)-a;if(left<=0)d.items.remove(m);else d.items.put(m,left);storage(p,d);store.save();}}
 private void item(Inventory i,int n,Material m,String name,String... lore){ItemStack x=new ItemStack(m);ItemMeta z=x.getItemMeta();z.setDisplayName(name);z.setLore(Arrays.asList(lore));x.setItemMeta(z);i.setItem(n,x);}}
